language: node_js
dist: trusty
os: linux
env:
  global:
    - ARDUINO_VERSION=1.8.5
node_js:
  - "node"
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - npm install -g polymer-cli
  - npm install -g polymer-bundler
  - ln -s $PWD /usr/local/share/arduino/libraries/log4Esp
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266;
  - arduino --pref "boardsmanager.additional.urls=" --save-prefs;
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - source $TRAVIS_BUILD_DIR/travis/build.sh
  - cd pixel-art-app/
  - polymer install -v
before_deploy:
  - mkdir build
  - polymer-bundler index.html --inline-scripts --inline-css --strip-comments > build/index.html
deploy:
  provider: pages
  github-token: $GH_PAGES_TOKEN
  local-dir: pixel-art-app/build/
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: master