dist: trusty
language: cpp
env:
  global:
    - ARDUINO_VERSION=1.8.5
node_js:
  - "node"
  - "stable"
stages:
- deploy
- ':deploy it to GH-PAGES'
cache:
  directories:
    - node_modules
before_install:
  - wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - npm install -g polymer-cli
  - mkdir -p ~/Arduino/libraries
  - ln -s $PWD ~/Arduino/libraries/.
  - git clone https://github.com/hunsalz/esp8266utils.git ~/Arduino/libraries/esp8266utils
  - arduino --install-library "log4Esp:1.0.0"
  - arduino --install-library "ArduinoJson:5.13.1"
  - git clone https://github.com/me-no-dev/ESPAsyncTCP.git ~/Arduino/libraries/ESPAsyncTCP
  - git clone https://github.com/me-no-dev/ESPAsyncWebServer.git ~/Arduino/libraries/ESPAsyncWebServer
  - arduino --install-library "FastLED:3.1.6"
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - source $TRAVIS_BUILD_DIR/travis/build.sh
  - cd pixel-art-app/
  - npm install
  - polymer build
  - mv build/public .
  - echo "<META http-equiv="refresh" content=\"0;URL=public/demo/\">" >index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAGES_TOKEN
  keep-history: true
  local-dir: .
  verbose: true
  on:
    branch: master